services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform_app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - postgres
      - mysql
      - clickhouse
      - redis
      - nats
    networks:
      - platform_network
    profiles:
      - test
      
  postgres:
    image: postgres:15-alpine
    container_name: platform_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-go_platform}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - platform_network

  mysql:
    image: mysql:8.0
    container_name: platform_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DB:-go_platform}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - platform_network
    command: --default-authentication-plugin=mysql_native_password

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: platform_clickhouse
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-go_platform}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-admin}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-admin}
      CLICKHOUSE_LISTEN_HOST: 0.0.0.0
    ports:
      - "${CLICKHOUSE_PORT:-9000}:9000"
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - platform_network

  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly no --save "" --requirepass ""  
    container_name: platform_redis
    env_file:
      - .env
    environment:
      REDIS_ZONE_ID: "25"
      REDIS_PORT: "6379"
    ports:
      - "6379:6379"
    networks:
      - platform_network

  minio:
    image: quay.io/minio/minio
    container_name: platform_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"

  nats:
    image: nats:2.10-alpine
    container_name: platform_nats
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "${NATS_MONITOR_PORT:-8222}:8222"
    command: ["-m", "8222", "-js"]
    networks:
      - platform_network


volumes:
  postgres_data:
  mysql_data:
  clickhouse_data:
  redis_data:

networks:
  platform_network:
    driver: bridge
