services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: platform_app
    env_file:
      - .env-docker-ch
    ports:
      - "${SERVER_PORT:-8080}:8080"
      - "${GRPC_PORT:-50051}:50051"
    depends_on:
      - clickhouse
      - redis
      - minio
      - nats
    networks:
      - platform_network
    profiles:
      - test

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: platform_clickhouse
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-go_platform}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-admin}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-admin}
      CLICKHOUSE_LISTEN_HOST: 0.0.0.0
    ports:
      - "${CLICKHOUSE_PORT:-9000}:9000"
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - platform_network

  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly no --save "" --requirepass ""  
    container_name: platform_redis
    environment:
      REDIS_ZONE_ID: "25"
      REDIS_PORT: "6379"
    ports:
      - "6379:6379"
    networks:
      - platform_network

  minio:
    image: quay.io/minio/minio
    container_name: platform_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    networks:
      - platform_network

  nats:
    image: nats:2.10-alpine
    container_name: platform_nats
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "${NATS_MONITOR_PORT:-8222}:8222"
    command: ["-m", "8222", "-js"]
    networks:
      - platform_network

volumes:
  clickhouse_data:
  redis_data:

networks:
  platform_network:
    driver: bridge
