global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'go-platform'
    static_configs:
      - targets: ['app:8080']  # Your Go service in Docker
    metrics_path: '/metrics'
    scrape_interval: 5s
