global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'go-platform'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Your Go app metrics server
    metrics_path: '/'
    scrape_interval: 5s
